@tool
extends RefCounted

# Intentionally NO `class_name`: core Charon is bundled per-plugin (namespaced),
# so each Olympus tool preloads its own copy rather than sharing one global
# symbol. Reference via:  const NyxCharon = preload(".../core/charon.gd")

## Charon - core communication seam between Nyx and Godot.
##
## This is the STATELESS, static "core Charon" only: plugin↔Godot utilities, no
## registry, no event bus, no shared state. Each Olympus plugin bundles its own
## copy (namespaced). The full event-bus Charon is a separate, future standalone
## plugin; when it exists, the seams below hand off to it instead of acting
## directly.
##
## V1 publishes nothing on a bus. The signal name and payload shape below are
## fixed now as CONVENTION ONLY, so Full Charon (with Hephaestus and Iris as
## future subscribers) can route them later. Getting the name/payload right
## matters more than any V1 code here.

## Convention-only event name. Not emitted in V1 - reserved for Full Charon.
const SIGNAL_SHADER_UPDATED := "nyx:shader_updated"

## Provenance stamp written as the first line of an exported .gdshader. Gates the
## artifact -> Nyx navigation (we only offer "Open in Nyx" for shaders we authored).
const PROVENANCE_PREFIX := "// nyx_source: "

## Human-readable line(s) following the stamp - Godot's built-in shader/text editor
## always wins double-click focus for Shader-typed resources (confirmed, no addon
## override exists - see CLAUDE.md's Known Gotchas), so anyone who lands here via
## double-click needs a pointer back to the graph. Written into both the .nyx's
## baked compiled_code (nyx_main._serialize_graph_for_save) and the importer's
## no-compiled-code-yet placeholder (core/nyx_shader_importer.gd) - not the
## exported .gdshader, which already has its own distinct warning line and whose
## own "Open in Nyx" flow was never affected by any of this.
const NAV_HINT := "// This shader was generated by Nyx. To edit it visually, right-click\n// this file in the FileSystem dock and choose \"Open in Nyx\" (for now).\n"

## Markers bracketing the embedded recovery graph in an exported .gdshader (see
## NyxSerializer.write_shader). Godot's shader compiler ignores comments;
## between the two markers is exactly one line - a compact JSON dump of the
## same serialize-dict shape core/nyx_serializer.gd round-trips for a `.nyx`
## file (minus compiled_code - the shader IS the compiled code here). This is a
## recovery fallback only: the linked `.nyx` stays primary whenever it still
## resolves (see plugin.gd._open_in_nyx). The graph reflects only the last
## Update - hand edits made directly to the GLSL are not captured, and the
## next Update after a recovery overwrites them.
const GRAPH_BEGIN := "// nyx_graph_begin"
const GRAPH_END := "// nyx_graph_end"


## Reads the provenance stamp from an exported shader, returning the source .nyx
## path (res://…) or "" if the file isn't a Nyx-authored shader. The stamp is
## always the first line (see nyx_main._write_shader_file).
static func read_nyx_source(shader_path: String) -> String:
	if not shader_path.ends_with(".gdshader"):
		return ""
	if not FileAccess.file_exists(shader_path):
		return ""
	var f := FileAccess.open(shader_path, FileAccess.READ)
	if f == null:
		return ""
	var first := f.get_line()
	f.close()
	if first.begins_with(PROVENANCE_PREFIX):
		return first.substr(PROVENANCE_PREFIX.length()).strip_edges()
	return ""


## Same check as read_nyx_source(), but against an already-loaded Shader's code
## string instead of a file on disk. A `.nyx` imports directly as a Shader (see
## core/nyx_shader_importer.gd) with the same provenance line baked in as line 1
## by nyx_main's _serialize_graph_for_save() - so this one helper covers both
## re-entry paths (direct .nyx, exported .gdshader) uniformly.
static func read_nyx_source_from_code(code: String) -> String:
	var first := code.get_slice("\n", 0)
	if first.begins_with(PROVENANCE_PREFIX):
		return first.substr(PROVENANCE_PREFIX.length()).strip_edges()
	return ""


## Scans an exported shader for the embedded recovery graph (see GRAPH_BEGIN/
## GRAPH_END above) and parses the JSON line between them. Returns an empty
## Dictionary if the markers aren't found or the JSON fails to parse - callers
## treat that as "no recovery available," not an error.
static func read_embedded_graph(shader_path: String) -> Dictionary:
	if not FileAccess.file_exists(shader_path):
		return {}
	var text := FileAccess.get_file_as_string(shader_path)
	var start := text.find(GRAPH_BEGIN)
	if start == -1:
		return {}
	var end := text.find(GRAPH_END, start)
	if end == -1:
		return {}
	var block := text.substr(start + GRAPH_BEGIN.length(), end - (start + GRAPH_BEGIN.length()))
	var json_line := block.strip_edges().trim_prefix("//").strip_edges()
	var parsed = JSON.parse_string(json_line)
	if parsed is Dictionary:
		return parsed
	return {}


## Push freshly-compiled shader code into the live, loaded Shader resource at
## `shader_path`. Because Godot caches resources, mutating that loaded instance's
## `.code` propagates in-memory to every material in the scene that references it
## - the live-link update, no disk write.
##
## `material` is the source of truth for the code (the live preview material,
## whose shader carries the latest compile). Returns true on success.
##
## Future: if Full Charon is present, emit nyx:shader_updated on its bus with
## payload { shader_path, material } and let it route, instead of acting here.
static func notify_shader_updated(shader_path: String, material: Material) -> bool:
	if shader_path.is_empty() or material == null:
		return false
	if not material is ShaderMaterial:
		return false
	var src_shader: Shader = (material as ShaderMaterial).shader
	if src_shader == null:
		return false
	if not ResourceLoader.exists(shader_path):
		return false
	var target: Shader = ResourceLoader.load(shader_path, "Shader")
	if target == null:
		return false
	if target.code != src_shader.code:
		target.code = src_shader.code
	return true


## Editor layout focus - reclaim screen space while an Olympus main-screen tool is
## visible by collapsing Godot's docks + bottom panel via distraction-free mode.
## Distraction-free is the only clean public API for this (all-or-nothing - there's
## no public per-dock control; hiding individual docks means walking the editor's
## internal tree, which is fragile). Non-destructive: capture the prior state on
## enter, restore it on leave. Stateless - the caller holds the returned token and
## passes it back to exit_focus_layout() so this stays free of shared state.

## Enter focus layout. Returns the prior distraction-free state for later restore.
static func enter_focus_layout() -> bool:
	var was_on := EditorInterface.is_distraction_free_mode_enabled()
	if not was_on:
		EditorInterface.set_distraction_free_mode(true)
	return was_on


## Restore the layout captured by enter_focus_layout(). Pass the value it returned.
static func exit_focus_layout(prior_distraction_free: bool) -> void:
	if EditorInterface.is_distraction_free_mode_enabled() != prior_distraction_free:
		EditorInterface.set_distraction_free_mode(prior_distraction_free)
